version: "3.2"
services:
  rest:
      build: 
        context: ./janken-api
        dockerfile: Dockerfile
      ports:
        - "3001:3005"
      depends_on:
        - mongodb
      environment:
        NODE_ENV: dev
  web:
      build: 
        context: ./janken-spa
        dockerfile: Dockerfile
      ports:
        - "3000:80"
  mongodb:
      image: mongo:latest
      container_name: "mongodb"
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
      volumes:
        - ./janken-data:/data/db
      ports:
          - 27017:27017
      command: mongod --smallfiles --logpath=/dev/null # --quiet